
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-xiaoke-xiaoke-com-v1-xiaoke
  failurePolicy: Fail
  name: mxiaoke.kb.io
  rules:
  - apiGroups:
    - xiaoke.xiaoke.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - xiaokes
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-xiaoke-xiaoke-com-v1-xiaoke
  failurePolicy: Fail
  name: vxiaoke.kb.io
  rules:
  - apiGroups:
    - xiaoke.xiaoke.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - xiaokes
  sideEffects: None
