
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - xiaoke.xiaoke.com
  resources:
  - xiaokes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - xiaoke.xiaoke.com
  resources:
  - xiaokes/finalizers
  verbs:
  - update
- apiGroups:
  - xiaoke.xiaoke.com
  resources:
  - xiaokes/status
  verbs:
  - get
  - patch
  - update
