# permissions for end users to view xiaokes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: xiaoke-viewer-role
rules:
- apiGroups:
  - xiaoke.xiaoke.com
  resources:
  - xiaokes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - xiaoke.xiaoke.com
  resources:
  - xiaokes/status
  verbs:
  - get
